### PR TITLE
fix(IOS-compatibility): replacing events package by native EventTarge…

### PR DESCRIPTION
**Pull request by Load-Ma**
The events package was not available in the iOS version of Obsidian, so I replaced it with the native EventTarget class. Here's what I did:

- Created a new class, "CustomEventTarget," in the /modules folder.
- Implemented all the methods used by the events package in the new CustomEventTarget class.
- Now, the plugin has the same code as before to emit, listen to, and remove events, but it uses the new CustomEventTarget class instead of the "events" package.

Feel free to ask anything about the code or if I need to move the new CustomEventTarget class to another folder!

### CODE REVIEW

**Comment by turulix** [comment]
Looks good so far, mind removing the .md files?

**Comment by Load-Ma** [comment]
> Looks good so far, mind removing the .md files?

Do you want me to remove all .md  files ? or just some of them ?

**Comment by turulix** [comment]
All of them, i dont see why they should be there. Or am i missing something?

**Comment by Load-Ma** [comment]
now it should be good

**Pull request merged**
